### ISSUE TITLE
Could not import files

### ISSUE THREAD

**Issue by Hattricx** [fat-dash/fat-dash#12]
When uploading files I get an error saying "I could not import 1 files", where the number correspond to the number of files I'm uploading.

I'm unable to post the CSV files here.

**Comment by nahuef** [comment]
Yeap, Koovak update changed the CSV format and now they dont work with the app anymore.
Project seems abandoned and source code is not here to make necessary changes to have it working again.

**Comment by Hattricx** [comment]
Kovaak has a built in stat viewer now so I guess this isn't necessary anymore.
