### ISSUE TITLE
Spinning as soon as I load in

### ISSUE THREAD

**Issue by Xeniity** [fat-dash/fat-dash#7]
I just bought this and my character keeps spinning to the left no matter what settings I change

**Comment by flexxis** [comment]
Hey,
I guess you mean the main game and not the dashboard app https://fat-dash.github.io/? Then you should rather contact the support of FPS Aim Trainer via one of the channels (Steam, Discord, Reddit etc.). Let me emphasize that this is only a community project contributing to the main game. I do not have any monetary or similar relation to the main game owner.

Hope, I could help regardless.
