### ISSUE TITLE
Unable to import .csv from the game version 2.0.1.0 (open beta)

### ISSUE THREAD

**Issue by s0bol** [fat-dash/fat-dash#9]
It is impossible to import .csv stats from the game version 2.0.1.0 (current open beta).
I was unable to import stats from following scenarios: 1wall 1 target, Tile frenzy - strafing 01, 1wall6targets, Close Long strafes, Cata IC Long strafes. I had no issues with Vertical long strafes and fuglaaXYLongstrafes.

When I quickly went through the bare .csv I found that all abovementioned problematic scenarios logs every kill details. What differs however between the 2.0.1.0 logs and 2.0.0.2 (current non-beta version) logs is the time format.
2.0.1.0 uses: 18:52:13.555
2.0.0.2 uses: 18:52:13:555

Newer version uses dot instead of colon to separate thousands of a seconds, what I suspect is causing problems.

**Comment by arthur-st** [comment]
Issue persists with stable `2.0.1.0` release of the trainer, @flexxis

**Comment by sidtheone** [comment]
Temporary format converter at below location. It wasn't possible for me to read current code as its kind of packaged. So ended up writing a temporary file converter in python.

https://github.com/sidtheone/fat-dash-fix

**Comment by flexxis** [comment]
Good news: The app should be now usable with csv files that are 2.0.1.0 or higher!

In addition, there is something important to mention: 
A couple of "intermediate" csv files around version 2.0.1.0 might still produce an error. KovaaK mentioned, these files were produced from the game during active beta development phase. So either delete these or try out [above converter](https://github.com/fat-dash/fat-dash/issues/9#issuecomment-626975358). Big thanks to @sidtheone for having provided this tool.

The parser rules are:

- The exported statistics csv files previously had timestamps exported in this format: hh:mm:ss:mss.  
- The new exported statistics csv files (2.0.1.0) are: hh:mm:ss.mss (the last colon changed to a period), so 20:52:13:695 -> 20:52:13.695.  

I am closing this issue for now, feel free to open a new one, if there still should be issues.
